#!/usr/bin/env python3
# -*- coding: utf-8 -*-
print("🍪 B站Cookie获取详细指导")
print("=" * 60)
print()
print("📋 【第一步：登录B站】")
print("1. 打开浏览器(推荐Chrome/Edge)")
print("2. 访问: https://www.bilibili.com")
print("3. 点击右上角登录你的B站账号")
print("4. 确保登录成功，能看到你的头像")
print()
print("🔧 【第二步：打开开发者工具】")
print("1. 在B站页面按 F12 键")
print("2. 或者右键点击页面 -> 检查元素")
print("3. 切换到 'Network'(网络) 标签页")
print("4. 如果是中文界面，找到 '网络' 标签")
print()
print("🔄 【第三步：刷新页面获取请求】")
print("1. 确保Network标签已选中")
print("2. 按 Ctrl+R 或 F5 刷新页面")
print("3. 你会看到很多网络请求出现")
print()
print("🕵️ 【第四步：找到Cookie信息】")
print("1. 在请求列表中找到第一个请求(通常是'www.bilibili.com')")
print("2. 点击这个请求")
print("3. 在右侧找到 'Request Headers'(请求标头)")
print("4. 找到 'Cookie:' 这一行")
print()
print("📝 【第五步：复制关键Cookie值】")
print("在Cookie这一行中，找到并复制以下值：")
print()
print("   🔑 SESSDATA=xxxxxxx")
print("   🔑 bili_jct=xxxxxxx")
print("   🔑 DedeUserID=245011151 (应该是你的UID)")
print("   🔑 DedeUserID__ckMd5=xxxxxxx")
print("   🔑 buvid3=xxxxxxx")
print("   🔑 buvid4=xxxxxxx")
print()
print("💡 【Cookie格式示例】")
print("Cookie行大概长这样:")
print("Cookie: SESSDATA=abc123; bili_jct=def456; DedeUserID=245011151; ...")
print()
print("你需要复制每个=号后面的值，例如:")
print("  SESSDATA 的值是: abc123")
print("  bili_jct 的值是: def456")
print("  等等...")
print()
print("🔧 【第六步：更新config.txt】")
print("将获取的Cookie值填入config.txt的[COOKIES]部分：")
print()
print("[COOKIES]")
print("SESSDATA = 你复制的SESSDATA值")
print("bili_jct = 你复制的bili_jct值")
print("DedeUserID = 245011151")
print("DedeUserID__ckMd5 = 你复制的DedeUserID__ckMd5值")
print("buvid3 = 你复制的buvid3值")
print("buvid4 = 你复制的buvid4值")
print()
print("🎉 【完成后测试】")
print("更新config.txt后，运行:")
print("   python test_full_auth.py")
print()
input("按Enter键退出...") 